### ISSUE TITLE
Let bot make github issue via command

### ISSUE THREAD

**Issue by therealmistericraft** [therealmistericraft/MisteriBot#11]
Bot command makes web request to ifttt (webhook), then create a new github issue with ifttt

**Comment by therealmistericraft** [comment]
If I did this, anyone could write illegal things as issue under my account and name.

**Comment by ghost** [comment]
You can use [this](https://gist.github.com/joseywoermann/b6430642b538437cb60fb11e995c7581) and use a second account to implement this feature.

**Comment by ghost** [comment]
> You can use [this](https://gist.github.com/joseywoermann/b6430642b538437cb60fb11e995c7581) and use a second account to implement this feature.

I could also potentially use my second account to make this for your bot.

**Comment by therealmistericraft** [comment]
No, I do not want to have this feature anymore. But thank you for your tips.
