### ISSUE TITLE
welcome-message

### ISSUE THREAD

**Issue by joseywoermann** [therealmistericraft/MisteriBot#27]
The bot sends the welcome-message, even if you join for example, your testserver. (You know what I mean)

**Comment by joseywoermann** [comment]
Do you want to test this now?

**Comment by joseywoermann** [comment]
I have time.

**Comment by therealmistericraft** [comment]
I can only test it while it's running on the main instance.

**Comment by joseywoermann** [comment]
Is this a yes or a no?

**Comment by therealmistericraft** [comment]
A no.

**Comment by joseywoermann** [comment]
> I can only test it while it's running on the main instance.

Why?

**Comment by joseywoermann** [comment]
?

**Comment by therealmistericraft** [comment]
Because the welcome message should only be shown on the MisteriCraft community server and I do not want to have the work in progress instance on it.

**Comment by therealmistericraft** [comment]
Note to myself:
This feature may won't work at all, because the welcome channel is not there anymore. Does the message content, that a user has to accept the rules?

**Comment by joseywoermann** [comment]
> Note to myself:
> This feature may won't work at all, because the welcome channel is not there anymore. Does the message content, that a user has to accept the rules?

What do you mean with that? I don't understand...

**Comment by therealmistericraft** [comment]
I said its a note for myself, you do not have to understand it.

**Comment by joseywoermann** [comment]
> Does the message content, that a user has to accept the rules?

This sentence is missing a verb. (Does the message-content _do what?_, ...

**Comment by therealmistericraft** [comment]
You are wrong. Content is a verb too. It means "beinhalten"

**Comment by joseywoermann** [comment]
It is "contains"

**Comment by ghost** [comment]
Btw. This is still a thing.

**Comment by therealmistericraft** [comment]
I don't think so. When adding MisteriBot to school it server, I did not get a welcome message. You have to know that I am pretty confused about the progress of MisteriBot and the script at all. Looks like I finish the ground construction of schoolbot in the next couple days, from which I could copy and paste parts like a rewrite.

**Comment by ghost** [comment]
I got the message today.
![image](https://user-images.githubusercontent.com/67111271/103243387-008c2180-495a-11eb-915b-477eef1c9c3a.png)

**Comment by therealmistericraft** [comment]
I thought about an other message, I am sorry!

**Comment by ghost** [comment]
> Note to myself:
> This feature may won't work at all, because the welcome channel is not there anymore. Does the message contain, that a user has to accept the rules?
> 

Why don't you just check which guild the user joined?

**Comment by ghost** [comment]
After 6 months, this has finally been fixed.
