### ISSUE TITLE
Suggestion regarding labels

### ISSUE THREAD

**Issue by joseywoermann** [therealmistericraft/MisteriBot#29]
I suggest adding/removing labels, such as "spelling-mistake", "outage" and stuff like that. For example, a spelling mistake or an outage can not _really_ be considered a bug.

**Comment by therealmistericraft** [comment]
This is a really good idea, thank you! Maybe you know, how customers (I mean other GitHub users with this) can add labels too?

**Comment by joseywoermann** [comment]
I don´t think external poeple can just randomly add or remove labels, that would be kinda dumb. I think that, if the person is a "collaborater" in the specific repository, they can add labels, but I´m not sure.
