### ISSUE TITLE
tHeRe Is a bUG

### ISSUE THREAD

**Issue by joseywoermann** [therealmistericraft/MisteriBot#35]
When executing i.e. _*help_ or _*changelog_, the bot adds the "close"-Button 2 times.

![Screenshot_2020-08-19-21-38-49-79_572064f74bd5f9fa804b05334aa4f912.jpg](https://user-images.githubusercontent.com/67111271/90681863-60641480-e264-11ea-9b14-1bcc54276108.jpg)

**Comment by therealmistericraft** [comment]
Already fixed it. There isn't a issue because it was before joining GitHub.

**Comment by joseywoermann** [comment]
When will you release V 5.0?

**Comment by therealmistericraft** [comment]
I cannot say right now, maybe in like 2 Weeks or later. School is very stressful.

**Comment by ghost** [comment]
> Already fixed it. There isn't a issue because it was before joining GitHub.

This is still a thing, have you not updated the bot in the last 5 months?

**Comment by therealmistericraft** [comment]
> This is still a thing, have you not updated the bot in the last 5 months?

Yup

**Comment by ghost** [comment]
> > This is still a thing, have you not updated the bot in the last 5 months?
> 
> Yup

_You should probably do that rather soon._

**Comment by therealmistericraft** [comment]
Thats not possible, I have no other working version, I have to rewrite the bot completely

**Comment by ghost** [comment]
> Thats not possible, I have no other working version, I have to rewrite the bot completely

Can't you just take the working bot that's on the Raspberry Pi and add the new features?

**Comment by therealmistericraft** [comment]
The problem with this is, I do not know how many features I already added to the newest version... I want to rewrite it anyway, so I will do it.

**Comment by ghost** [comment]
> The problem with this is, I do not know how many features I already added to the newest version... I want to rewrite it anyway, so I will do it.

So... Next version coming in 2 years?
/s

**Comment by therealmistericraft** [comment]
possible.
