### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by joseywoermann** [therealmistericraft/MisteriBot#39]
In the changelog for v4 it says navEnlos, but it's called navnlos

**Comment by joseywoermann** [comment]
Have you seen this? @therealmistericraft

**Comment by therealmistericraft** [comment]
Not until now, but I don't know what you mean

**Comment by joseywoermann** [comment]
![IMG_20200910_171716.jpg](https://user-images.githubusercontent.com/67111271/92752762-82474780-f389-11ea-9978-9e88bd3614b7.jpg)
