### ISSUE TITLE
Controls don't work

### ISSUE THREAD

**Issue by ghost** [therealmistericraft/MisteriBot#47]
### Description
Controls in *help and *changelog don't work

### Issue Source
- execute `*help` or `*changelog`- press either the ➡️ or ⬅️ button

### Current behavior
The message is not being updated
The button to delete the message still works

### Expected behavior
The mesaage should be updated and show the second page 

### Device and software
- RMX2063 running RMX2063_11_A.32 
- Discord Version: 52.3 

### How to fix?
https://discordpy.readthedocs.io/en/latest/api.html?highlight=on_raw_reaction_add#discord.Intents.reactions
In API V1.6.0, reaction intent has to be enabled.

**Comment by ghost** [comment]
- updated bug report

**Comment by therealmistericraft** [comment]
Thank you for your bug report. I think the issue is because of the new API version. Unlikely, this issue can't be fixed until 18th December 2020.

**Comment by joseywoermann** [comment]
> Thank you for your bug report. I think the issue is because of the new API version. Unlikely, this issue can't be fixed until 18th December 2020.

*unfortunately, not unlikely

**Comment by therealmistericraft** [comment]
@joseywoermann As I thought, the issue is because API Version 1.6.0. I edited your issue for how to fix. Maybe it is so at navnløs too?

**Comment by therealmistericraft** [comment]
> Thank you for your bug report. I think the issue is because of the new API version. Unlikely, this issue can't be fixed until 18th December 2020.

Because it's an easy fix, I will probably work on it today.

**Comment by ghost** [comment]
@therealmistericraft You had not had intents enabled until now?

**Comment by therealmistericraft** [comment]
> @therealmistericraft You had not had intents enabled until now?

Yup
