### ISSUE TITLE
Create an helper.bat for self-hosting the bot

### ISSUE THREAD

**Issue by therealmistericraft** [therealmistericraft/MisteriBot#56]
In order to host MisteriBot yourself, you have to have installed python, discord.py and need some files in .gitignore, for example the token file. The bat could install python correctly and create the files for tokens, as well as asking for the token to write it directly in it.

**Comment by ghost** [comment]
Implemented in #62.

**Comment by ghost** [comment]
Why is this still open? @therealmistericraft
