### ISSUE TITLE
Outage

### ISSUE THREAD

**Issue by ghost** [therealmistericraft/MisteriBot#57]
### Date & Time
- Time Zone: CEST (UTC+2)
- Date (YYYY-MM-DD): 2021-03-30
- Time: 09:21

### Type of Outage
- [x] offline
- [ ] not responding
- [ ] other:

### Does it work on other guilds/shards/servers?
- [ ] Yes
- [x] No
- [ ] Not shure

### Other
- Guild ID (Leave emty if you want): all guilds

**Comment by therealmistericraft** [comment]
Thank you for your report! Turns out that the raspberry pi, that runs the bot, installed an OS-Update. Bot will be online again shortly!
