### ISSUE TITLE
Support Slash Commands

### ISSUE THREAD

**Issue by ghost** [therealmistericraft/MisteriBot#58]
**Is your feature request related to a problem? Please describe.**
Currently, you almost always have to look at the help-menu or remember the syntax. If you get the syntax even slightly wrong, nothing works and you don't get an error message which explains what happened.

**Describe the solution you'd like**
Add Slash Commands. These make it obvious how to use the command (like seen below), and prevent errors, because they can't be send if you get the syntax wrong.
![image](https://user-images.githubusercontent.com/67111271/118362933-3b51c780-b592-11eb-9dff-ad2ccff11946.png)

**Describe alternatives you've considered**
Add proper Error-Messages, but these don't make the syntax clear.

**Additional context**
Slash Commands are currently **not** natively supported by the discord.py-library, but you use them easily with [this library](https://pypi.org/project/discord-py-slash-command/).

**Comment by therealmistericraft** [comment]
This wont be implemented until it is officially supported.

**Comment by therealmistericraft** [comment]
But thank you for your hint and really good description!

**Comment by ghost** [comment]
> This wont be implemented until it is officially supported.

Why not?

(And also, you can keep this issue open until you implement it, so you don't forget it.)

**Comment by therealmistericraft** [comment]
I personally do not like slash commands and do not want to change my code habits. Also, I do not think it is that important to use 3rd party libraries, from which I know nothing (how they work, if I can trust them, ...)

I do not have to have this issue opened, I sorted them in Projects so that I see it when it is time for implementing slash commands.

**Comment by ghost** [comment]
> Also, I do not think it is that important to use 3rd party libraries, from which I know nothing (how they work, if I can trust them, ...)

You already use a lot of 3rd party libraries, and there is a good documentation.

**Comment by ghost** [comment]
> I personally do not like slash commands

interesting, why not?

**Comment by therealmistericraft** [comment]
Its like you have multiple bots with the same prefix and you cant find the right bot, I hate the design of the slash command interface (too few contrasts) and do not get the syntax from the examples or annotations, which are in this interface

**Comment by ghost** [comment]
Remember that you'll have to enable the privileged `message content` intent or transition to Slash Commands in the "near" future.
https://support-dev.discord.com/hc/en-us/articles/4404772028055
