### ISSUE TITLE
Spelling mistake in the wiki

### ISSUE THREAD

**Issue by ghost** [therealmistericraft/MisteriBot#60]
### Description
On [this](https://github.com/therealmistericraft/MisteriBot/wiki#translators-needed) page, it says `should be avaiable to`, but "available" is spelled incorrectly.

### Attachements
![image](https://user-images.githubusercontent.com/67111271/119164161-69387f80-ba5c-11eb-9002-b14af90a075d.png)

### How to fix?
Just spell it correctly.

**Comment by therealmistericraft** [comment]
Fixed! Thanks for your report.
